export const TACTILE_QUESTIONS = [
    {
        id: 29,
        key: 'q29',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Avoids getting "messy" (for example, in paste, sand, finger paint, glue, tape)',
    },
    {
        id: 30,
        key: 'q30',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Expresses distress during grooming (for example, fights or cries during haircutting, face washing, fingernail cutting)',
    },
    {
        id: 31,
        key: 'q31',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Prefers long-sleeved clothing when it is warm or short sleeves when it is cold',
    },
    {
        id: 32,
        key: 'q32',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Expresses discomfort at dental work or toothbrushing (for example, cries or fights)',
    },
    {
        id: 33,
        key: 'q33',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Is sensitive to certain fabrics (for example, is particular about certain clothes or bedsheets)',
    },
    {
        id: 34,
        key: 'q34',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Becomes irritated by shoes or socks',
    },
    {
        id: 35,
        key: 'q35',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Avoids going barefoot, especially in sand or grass',
    },
    {
        id: 36,
        key: 'q36',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Reacts emotionally or aggressively to touch',
    },
    {
        id: 37,
        key: 'q37',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Withdraws from splashing water',
    },
    {
        id: 38,
        key: 'q38',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Has difficulty standing in line or close to other people',
    },
    {
        id: 39,
        key: 'q39',
        type: 'L',
        category: 'tactile_sensitivity',
        label: 'Rubs or scratches out a spot that has been touched',
    },
    {
        id: 40,
        key: 'q40',
        type: 'H',
        category: 'tactile_seeking',
        label: 'Touches people and objects to the point of irritating others',
    },
    {
        id: 41,
        key: 'q41',
        type: 'H',
        category: 'tactile_seeking',
        label: 'Displays unusual need for touching certain toys, surfaces, or textures (for example, constantly touching objects)',
    },
    {
        id: 42,
        key: 'q42',
        type: 'H',
        category: 'tactile_processing',
        label: 'Decreased awareness of pain and temperature',
    },
    {
        id: 43,
        key: 'q43',
        type: 'H',
        category: 'tactile_processing',
        label: "Doesn't seem to notice when someone touches arm or back (for example, unaware)",
    },
    {
        id: 44,
        key: 'q44',
        type: 'H',
        category: 'tactile_seeking',
        label: 'Avoids wearing shoes; loves to be barefoot',
    },
    {
        id: 45,
        key: 'q45',
        type: 'H',
        category: 'tactile_seeking',
        label: 'Touches people and objects',
    },
    {
        id: 46,
        key: 'q46',
        type: 'H',
        category: 'tactile_processing',
        label: "Doesn't seem to notice when face or hands are messy",
    },
];

export const SCALE_OPTIONS = [
    { label: 'Always', value: 1 },
    { label: 'Frequently', value: 2 },
    { label: 'Occasionally', value: 3 },
    { label: 'Seldom', value: 4 },
    { label: 'Never', value: 5 },
];
