export const MOVEMENT_SAFETY_QUESTIONS = [
    {
        id: 75,
        key: 'q75',
        type: 'L',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Seems accident-prone',
    },
    {
        id: 76,
        key: 'q76',
        type: 'L',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Hesitates going up or down curbs or steps (for example, is cautious, stops before moving)',
    },
    {
        id: 77,
        key: 'q77',
        type: 'L',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Fears falling or heights',
    },
    {
        id: 78,
        key: 'q78',
        type: 'L',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Avoids climbing/jumping or avoids bumpy/uneven ground',
    },
    {
        id: 79,
        key: 'q79',
        type: 'L',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Holds onto walls or banisters (for example, clings)',
    },
    {
        id: 80,
        key: 'q80',
        type: 'H',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Takes excessive risks during play (for example, climbs high into a tree, jumps off tall furniture)',
    },
    {
        id: 81,
        key: 'q81',
        type: 'H',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Takes movement or climbing risks during play that compromise personal safety',
    },
    {
        id: 82,
        key: 'q82',
        type: 'H',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Turns whole body to look at you',
    },
    {
        id: 83,
        key: 'q83',
        type: 'H',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Seeks opportunities to fall without regard to personal safety',
    },
    {
        id: 84,
        key: 'q84',
        type: 'H',
        unicode: '26A0',
        category: 'movement_safety',
        label: 'Appears to enjoy falling',
    },
];
export const SCALE_OPTIONS = [
    { label: 'Always', value: 1 },
    { label: 'Frequently', value: 2 },
    { label: 'Occasionally', value: 3 },
    { label: 'Seldom', value: 4 },
    { label: 'Never', value: 5 },
];
