export const ORAL_SENSORY_QUESTIONS = [
    {
        id: 54,
        key: 'q54',
        type: 'L',
        unicode: '1F446',
        category: 'oral_sensitivity',
        label: 'Gags easily with food textures or food utensils in mout±',
    },
    {
        id: 55,
        key: 'q55',
        type: 'L',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Avoids certain tastes or food smells that are typically part of children`s diets',
    },
    {
        id: 56,
        key: 'q56',
        type: 'L',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Will only eat certain tastes',
    },
    {
        id: 57,
        key: 'q57',
        type: 'L',
        unicode: '1F446',
        category: 'oral_sensitivity',
        label: 'Limits self to particular food textures/temperatures',
    },
    {
        id: 58,
        key: 'q58',
        type: 'L',
        unicode: '1F446',
        category: 'oral_sensitivity',
        label: 'Picky eater, especially regarding food textures',
    },
    {
        id: 59,
        key: 'q59',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Routinely smells nonfood object',
    },
    {
        id: 60,
        key: 'q60',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Shows strong preference for certain smells',
    },
    {
        id: 61,
        key: 'q61',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Shows strong preference for certain tastes',
    },
    {
        id: 62,
        key: 'q62',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Craves certain foods',
    },
    {
        id: 63,
        key: 'q63',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Seeks out certain tastes or smells',
    },
    {
        id: 64,
        key: 'q64',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Chews or licks on nonfood object',
    },
    {
        id: 65,
        key: 'q65',
        type: 'H',
        unicode: '1F444',
        category: 'oral_sensitivity',
        label: 'Mouths objects (for example, pencil, hands)',
    },
];

export const SCALE_OPTIONS = [
    { label: 'Always', value: 1 },
    { label: 'Frequently', value: 2 },
    { label: 'Occasionally', value: 3 },
    { label: 'Seldom', value: 4 },
    { label: 'Never', value: 5 },
];
