export const SENSORY_TONE_QUESTIONS = [
    {
        id: 66,
        key: 'q66',
        type: '',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Moves stiffly',
    },
    {
        id: 67,
        key: 'q67',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Tires easily, especially when standing or holding particular body positio',
    },
    {
        id: 68,
        key: 'q68',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Locks joints (for example, elbows, knees) for stability',
    },
    {
        id: 69,
        key: 'q69',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Seems to have weak muscle',
    },
    {
        id: 70,
        key: 'q70',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Has a weak grasp',
    },
    {
        id: 71,
        key: 'q71',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Can`t lift heavy objects (for example, weak in comparison to same age children',
    },
    {
        id: 72,
        key: 'q72',
        type: 'H',
        unicode: '1F6B9',
        category: 'sensory_processing_end_tone',
        label: 'Props to support self (even during activity)',
    },
    {
        id: 73,
        key: 'q73',
        type: 'H',
        unicode: '2192',
        category: 'sensory_processing_end_tone',
        label: 'Poor endurance/tires easily',
    },
    {
        id: 74,
        key: 'q74',
        type: 'H',
        unicode: '2192',
        category: 'sensory_processing_end_tone',
        label: 'Appears lethargic (for example, has no energy, is sluggish)',
    },
];

export const SCALE_OPTIONS = [
    { label: 'Always', value: 1 },
    { label: 'Frequently', value: 2 },
    { label: 'Occasionally', value: 3 },
    { label: 'Seldom', value: 4 },
    { label: 'Never', value: 5 },
];
