const API_URL = `${process.env.NEXT_PUBLIC_APP_URL}api/v1`;

/** Authentication Endpoint */
const LOGIN_ENDPOINT = `${API_URL}/login`;

/** Super Admin */

/** User Type */
const USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** Create User Type */
const CREATE_USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** Update User Type */
const UPDATE_USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** User Type Status Endpoint */
const USER_TYPE_STATUS_ENDPOINT = `${API_URL}/user-type/status`;

/** Role Type */
const ROLE_MASTER_ENDPOINT = `${API_URL}/roles`;
const ROLE_MASTER_STATUS_ENDPOINT = `${ROLE_MASTER_ENDPOINT}/status`;

/** Menu Master */
const MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Create Menu Master */

const CREATE_MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Update Menu Master */

const UPDATE_MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Menu Master Status Endpoint */

const MENU_MASTER_STATUS_ENDPOINT = `${API_URL}/menu/status`;

/** Super Admin Dashboard */
const DASHBOARD_API_URL = `${API_URL}/dashboard`;
const SUPER_ADMIN_COMPILENCE_TRACKER = `${DASHBOARD_API_URL}/compliance-tracker`;
const SUPER_ADMIN_DASHBOARD_STATS = `${DASHBOARD_API_URL}/stats`;
const SUPER_ADMIN_CENTER_OVERVIEW = `${DASHBOARD_API_URL}/center-user-overview`;
const SUPER_ADMIN_RECENT_ACTIVITY = `${DASHBOARD_API_URL}/recent-activity`;

/** Center Setup */
const CENTER_SETUP_LIST = `${API_URL}/center`;
const CENTER_ADMIN_DROPDOWN_LIST = `${API_URL}/center/admin`;
const CENTER_STATUS = `${API_URL}/center/status`;

/** Center Admin */
const CENTER_ADMIN_LIST = `${CENTER_ADMIN_DROPDOWN_LIST}/list`;
const CENTER_ADMIN_STATUS = `${DASHBOARD_API_URL}/center-setup/status-change`;

/** Center Admin Modal */
const CENTER_ADMIN_SPECIALIZATION = `${ROLE_MASTER_ENDPOINT}/specialization/`;
const CENTER_DROPDOWN_LIST_API = `${CENTER_SETUP_LIST}/list`;

/** Role Menu Mapping */
const ROLE_MENU_MAPPING = `${API_URL}/role-menu-mapping`;

/** Admin  */

/** Admin Dashboard */
const ADMIN_DASHBOARD_STATS = `${API_URL}/admin/stats`;
const ADMIN_UPCOMNG_SESSIONS = `${API_URL}/admin/upcoming-session`;
const ADMIN_RECENT_ACTIVITY = `${API_URL}/admin/recent-activity`;

/** Admin Session Management */
const ADMIN_SESSION_LIST = `${API_URL}/admin/dashboard/admin/session`;

/** Admin Staff Management */
const ADMIN_STAFF_MANAGEMENT_API = `${API_URL}/admin/dashboard/admin/staff`;
const ADD_NEW_STAFF_MEMBER = `${API_URL}/admin/staff`;

/** Language */
const ADMIN_LANGUAGE = `${API_URL}/admin/languages`;

/** Clinical Psychologist */
const CLINICAL_PSYCHOLOGIST_API_URL = `${API_URL}/clinical-psychologist`;
const GET_STUDENT_DETAIL_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/student`;
const SUBMIT_STUDENT_INFORMATION_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/student-information`;
const FORM_LIST_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/form-list`;
const SUBMIT_PERSONAL_BIRTH_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/personal-birth-history`;
const SUBMIT_POST_NATAL_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/post-natal-history`;
const SUBMIT_NEO_NATAL_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/neonatal-history`;
const SUBMIT_MEDICAL_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/medical-history`;
const SUBMIT_FAMILY_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/family-history`;
const SOCIAL_ENVIRONMENTAL_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/social-environmental-history`;
const SCHOLASTIC_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/scholastic-history`;
const PLAY_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/play-history`;
const GENERAL_OBSERVATION_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/general-observation`;
const SUBMIT_DIAGNOSIS_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/diagnosis`;
const SUBMIT_GROSS_MOTOR_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/gross-motor`;
const SUBMIT_DEVELOPMENTAL_FINE_MOTOR_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/fine-motor-cognition`;
const SUBMIT_SOCIAL_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/social-development`;
const SUBMIT_SELF_HELP_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/self-help`;
const SUBMIT_LANGUAGE_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/language`;
const GET_CLINICAL_PSYCHOLOGIST_FORM_DETAILS = `${CLINICAL_PSYCHOLOGIST_API_URL}/form`;

/** Psychologist */

const GET_PSYCHOLOGIST_ENDPOINT = `${API_URL}/admin/psychologist`;

/** Grade */

const GET_GRADE_ENDPOINT = `${API_URL}/admin/dashboard/admin/grade`;

/** School */

const GET_SCHOOL_ENDPOINT = `${API_URL}/admin/schools`;

/** ADD STUDENT */

const ADD_STUDENT_ENDPOINT = `${API_URL}/admin/students`;

/** Clinical Psychologist Dashboard */

const CLINICAL_PSYCHOLOGIST_DASHBOARD_STATS = `${API_URL}/clinical-psychologist/stats`;
const CLINICAL_PSYCHOLOGIST_UPCOMNG_SESSIONS = `${API_URL}/clinical-psychologist/upcoming-session`;
const CLINICAL_PSYCHOLOGIST_RECENT_ACTIVITY = `${API_URL}/clinical-psychologist/recent-activity`;

/** Clinical Psychologist Assessment */

const CLINICAL_PSYCHOLOGIST_ASSESSMENT_STUDENT_LIST = `${API_URL}/clinical-psychologist/assessments`;

/** Clinical Psychologist Track Session */

const CLINICAL_PSYCHOLOGIST_TRACK_SESSION = `${API_URL}/clinical-psychologist/intervention`;

export {
    LOGIN_ENDPOINT,
    USER_TYPE_ENDPOINT,
    ROLE_MASTER_ENDPOINT,
    MENU_MASTER_ENDPOINT,
    SUPER_ADMIN_COMPILENCE_TRACKER,
    SUPER_ADMIN_DASHBOARD_STATS,
    SUPER_ADMIN_CENTER_OVERVIEW,
    SUPER_ADMIN_RECENT_ACTIVITY,
    CREATE_USER_TYPE_ENDPOINT,
    UPDATE_USER_TYPE_ENDPOINT,
    USER_TYPE_STATUS_ENDPOINT,
    ROLE_MASTER_STATUS_ENDPOINT,
    CENTER_SETUP_LIST,
    CENTER_ADMIN_DROPDOWN_LIST,
    CENTER_STATUS,
    CENTER_ADMIN_LIST,
    ROLE_MENU_MAPPING,
    CENTER_ADMIN_SPECIALIZATION,
    CENTER_DROPDOWN_LIST_API,
    CREATE_MENU_MASTER_ENDPOINT,
    UPDATE_MENU_MASTER_ENDPOINT,
    MENU_MASTER_STATUS_ENDPOINT,
    CENTER_ADMIN_STATUS,
    ADMIN_DASHBOARD_STATS,
    ADMIN_UPCOMNG_SESSIONS,
    ADMIN_RECENT_ACTIVITY,
    ADMIN_SESSION_LIST,
    ADMIN_STAFF_MANAGEMENT_API,
    ADMIN_LANGUAGE,
    GET_PSYCHOLOGIST_ENDPOINT,
    ADD_NEW_STAFF_MEMBER,
    GET_STUDENT_DETAIL_API_URL,
    SUBMIT_STUDENT_INFORMATION_API_URL,
    FORM_LIST_API_URL,
    SUBMIT_PERSONAL_BIRTH_HISTORY_ENDPOINT,
    SUBMIT_POST_NATAL_ENDPOINT,
    SUBMIT_MEDICAL_HISTORY_ENDPOINT,
    SUBMIT_FAMILY_HISTORY_ENDPOINT,
    SOCIAL_ENVIRONMENTAL_HISTORY_ENDPOINT,
    SCHOLASTIC_HISTORY_ENDPOINT,
    PLAY_HISTORY_ENDPOINT,
    GENERAL_OBSERVATION_ENDPOINT,
    SUBMIT_DIAGNOSIS_ENDPOINT,
    GET_CLINICAL_PSYCHOLOGIST_FORM_DETAILS,
    SUBMIT_NEO_NATAL_ENDPOINT,
    SUBMIT_GROSS_MOTOR_DEVELOPMENT_ENDPOINT,
    SUBMIT_DEVELOPMENTAL_FINE_MOTOR_ENDPOINT,
    SUBMIT_LANGUAGE_DEVELOPMENT_ENDPOINT,
    SUBMIT_SOCIAL_DEVELOPMENT_ENDPOINT,
    SUBMIT_SELF_HELP_ENDPOINT,
    GET_GRADE_ENDPOINT,
    GET_SCHOOL_ENDPOINT,
    ADD_STUDENT_ENDPOINT,
    CLINICAL_PSYCHOLOGIST_DASHBOARD_STATS,
    CLINICAL_PSYCHOLOGIST_UPCOMNG_SESSIONS,
    CLINICAL_PSYCHOLOGIST_RECENT_ACTIVITY,
    CLINICAL_PSYCHOLOGIST_ASSESSMENT_STUDENT_LIST,
    CLINICAL_PSYCHOLOGIST_TRACK_SESSION,
};
