const API_URL = `${process.env.NEXT_PUBLIC_APP_URL}api/v1`;

/** Authentication Endpoint */
const LOGIN_ENDPOINT = `${API_URL}/login`;

/** Super Admin */

/** User Type */
const USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** Create User Type */
const CREATE_USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** Update User Type */
const UPDATE_USER_TYPE_ENDPOINT = `${API_URL}/user-type`;

/** User Type Status Endpoint */
const USER_TYPE_STATUS_ENDPOINT = `${API_URL}/user-type/status`;

/** Role Type */
const ROLE_MASTER_ENDPOINT = `${API_URL}/roles`;
const ROLE_MASTER_STATUS_ENDPOINT = `${ROLE_MASTER_ENDPOINT}/status`;

/** Menu Master */
const MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Create Menu Master */

const CREATE_MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Update Menu Master */

const UPDATE_MENU_MASTER_ENDPOINT = `${API_URL}/menu`;

/** Menu Master Status Endpoint */

const MENU_MASTER_STATUS_ENDPOINT = `${API_URL}/menu/status`;

/** Super Admin Dashboard */
const DASHBOARD_API_URL = `${API_URL}/dashboard`;
const SUPER_ADMIN_COMPILENCE_TRACKER = `${DASHBOARD_API_URL}/compliance-tracker`;
const SUPER_ADMIN_DASHBOARD_STATS = `${DASHBOARD_API_URL}/stats`;
const SUPER_ADMIN_CENTER_OVERVIEW = `${DASHBOARD_API_URL}/center-user-overview`;
const SUPER_ADMIN_RECENT_ACTIVITY = `${DASHBOARD_API_URL}/recent-activity`;

/** Center Setup */
const CENTER_SETUP_LIST = `${API_URL}/center`;
const CENTER_ADMIN_DROPDOWN_LIST = `${API_URL}/center/admin`;
const CENTER_STATUS = `${API_URL}/center/status`;

/** Center Admin */
const CENTER_ADMIN_LIST = `${CENTER_ADMIN_DROPDOWN_LIST}/list`;
const CENTER_ADMIN_STATUS = `${DASHBOARD_API_URL}/center-setup/status-change`;

/** Center Admin Modal */
const CENTER_ADMIN_SPECIALIZATION = `${ROLE_MASTER_ENDPOINT}/specialization/`;
const CENTER_DROPDOWN_LIST_API = `${CENTER_SETUP_LIST}/list`;

/** Role Menu Mapping */
const ROLE_MENU_MAPPING = `${API_URL}/role-menu-mapping`;

/** Admin  */

/** Admin Dashboard */
const ADMIN_DASHBOARD_STATS = `${API_URL}/admin/stats`;
const ADMIN_UPCOMNG_SESSIONS = `${API_URL}/admin/upcoming-session`;
const ADMIN_RECENT_ACTIVITY = `${API_URL}/admin/recent-activity`;

/** Admin Session Management */
const ADMIN_SESSION_LIST = `${API_URL}/admin/dashboard/admin/session`;

/** Admin Staff Management */
const ADMIN_STAFF_MANAGEMENT_API = `${API_URL}/admin/dashboard/admin/staff`;
const ADD_NEW_STAFF_MEMBER = `${API_URL}/admin/staff`;

/** Language */
const ADMIN_LANGUAGE = `${API_URL}/admin/languages`;

/** Clinical Psychologist */
const CLINICAL_PSYCHOLOGIST_API_URL = `${API_URL}/clinical-psychologist`;
const GET_STUDENT_DETAIL_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/student`;
const SUBMIT_STUDENT_INFORMATION_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/student-information`;
const FORM_LIST_API_URL = `${CLINICAL_PSYCHOLOGIST_API_URL}/form-list`;
const SUBMIT_PERSONAL_BIRTH_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/personal-birth-history`;
const SUBMIT_POST_NATAL_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/post-natal-history`;
const SUBMIT_NEO_NATAL_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/neonatal-history`;
const SUBMIT_MEDICAL_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/medical-history`;
const SUBMIT_FAMILY_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/family-history`;
const HOME_ENVIRONMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/home`;
const SOCIAL_ENVIRONMENTAL_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/social-environmental-history`;
const SCHOLASTIC_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/scholastic-history`;
const PLAY_HISTORY_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/play-history`;
const GENERAL_OBSERVATION_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/general-observation`;
const SUBMIT_DIAGNOSIS_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/diagnosis`;
const SUBMIT_GROSS_MOTOR_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/gross-motor`;
const SUBMIT_DEVELOPMENTAL_FINE_MOTOR_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/fine-motor-cognition`;
const SUBMIT_SOCIAL_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/social-development`;
const SUBMIT_SELF_HELP_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/self-help`;
const SUBMIT_LANGUAGE_DEVELOPMENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/language`;
const GET_CLINICAL_PSYCHOLOGIST_FORM_DETAILS = `${CLINICAL_PSYCHOLOGIST_API_URL}/form`;
const GET_STUDENT_ASSIGN_LIST_DETAILS = `${CLINICAL_PSYCHOLOGIST_API_URL}/assign-list`;
const MAP_STUDENT_ENDPOINT = `${CLINICAL_PSYCHOLOGIST_API_URL}/mapping/student`;
/** Psychologist */

const GET_PSYCHOLOGIST_ENDPOINT = `${API_URL}/admin/psychologist`;

/** Grade */

const GET_GRADE_ENDPOINT = `${API_URL}/admin/dashboard/admin/grade`;

/** School */

const GET_SCHOOL_ENDPOINT = `${API_URL}/admin/schools`;

/** ADD STUDENT */
const ADD_STUDENT_ENDPOINT = `${API_URL}/admin/students`;
const ASSIGN_STUDENT_SESSION = `${API_URL}/admin/assign-session`;
const GET_STUDENT_LIST = `${API_URL}/admin/students`;

/** Clinical Psychologist Dashboard */

const CLINICAL_PSYCHOLOGIST_DASHBOARD_STATS = `${API_URL}/clinical-psychologist/stats`;
const CLINICAL_PSYCHOLOGIST_UPCOMNG_SESSIONS = `${API_URL}/clinical-psychologist/upcoming-session`;
const CLINICAL_PSYCHOLOGIST_RECENT_ACTIVITY = `${API_URL}/clinical-psychologist/recent-activity`;

/** Clinical Psychologist Assessment */

const CLINICAL_PSYCHOLOGIST_ASSESSMENT_STUDENT_LIST = `${API_URL}/clinical-psychologist/assessments`;

/** Clinical Psychologist Track Session */

const CLINICAL_PSYCHOLOGIST_TRACK_SESSION = `${API_URL}/clinical-psychologist/intervention`;

/** Special Educator */

const SPECIAL_EDUCATOR_DASHBOARD_STATS = `${API_URL}/ot/stats`;
const SPECIAL_EDUCATOR_UPCOMING_SESSIONS = `${API_URL}/ot/upcoming-session`;
const SPECIAL_EDUCATOR_MY_STUDENTS = `${API_URL}/ot/students`;

const SPECIAL_EDUCATOR_ASSESSMENT_STUDENT_LIST = `${API_URL}/ot/students-assessment-list`;
const SPECIAL_EDUCATOR_INTERVENTION = `${API_URL}/ot/students-goal-list`;

const GET_SPECIAL_EDUCATOR_STUDENTS_DETAIL = `${API_URL}/special-educator/sec-student`;

const SUBMIT_SPECIAL_EDUCATOR_STUDENTS_DETAIL = `${API_URL}/special-educator/sec-student-information`;

/** Speech Therapist */
const OT_API_URL = `${API_URL}/ot`;
const CHIEF_COMPLAINTS_OBSERVATIONS_ENDPOINT = `${OT_API_URL}/chief-complaints-observations`;
const COMPLIANT_DETAIL_ANALYSIS_ENDPOINT = `${OT_API_URL}/chief-complaint-detail-analysis`;
const GROSS_MOTOR_SKILLS_ENDPOINT = `${OT_API_URL}/gross-motor-skills`;
const MUSCLE_TONE_ENDPOINT = `${OT_API_URL}/muscle-tone`;
const MUSCLE_STRENGTH_ENDPOINT = `${OT_API_URL}/muscle-strength`;
const ROM_ENDPOINT = `${OT_API_URL}/rom`;
const ENDURANCE_ENDPOINT = `${OT_API_URL}/endurance`;
const FINE_MOTOR_SKILLS_ENDPOINT = `${OT_API_URL}/fine-motor-skills`;
const REFLEXES_ENDPOINT = `${OT_API_URL}/reflexes`;
const SPEED_AND_AGILITY_ENDPOINT = `${OT_API_URL}/speed-agility`;
const GRASP_DEVELOPMENT_ENDPOINT = `${OT_API_URL}/grasp-development`;
const IN_HAND_DEVELOPMENT_ENDPOINT = `${OT_API_URL}/in-hand-manipulation`;
const CO_ORDINATION_ENDPOINT = `${OT_API_URL}/coordination`;
const NON_EQUILIBRIUM_ENDPOINT = `${OT_API_URL}/non-equilibrium-tests`;
const EQUILIBRIUM_ENDPOINT = `${OT_API_URL}/equilibrium-tests`;
const COGNITIVE_AND_PERCEPTUAL_SKILLS_ENDPOINT = `${OT_API_URL}/ot-cognitive-perceptual-skills`;
const COMMUNICATION_SKILLS_ENDPOINT = `${OT_API_URL}/communication-skills`;
const EMOTIONAL_AWARENESS_ENDPOINT = `${OT_API_URL}/emotional-awareness-expression`;
const SELF_REGULATION_ENDPOINT = `${OT_API_URL}/self-regulation-coping`;
const BEHAVIOR_ENDPOINT = `${OT_API_URL}/behavior`;
const SUBMIT_SOCIAL_SKILLS_ENDPOINT = `${OT_API_URL}/social-skills`;
const SUBMIT_PLAY_SKILLS_ENDPOINT = `${OT_API_URL}/play-skills`;
const ACTIVITY_OF_DAILY_LIVING_ENDPOINT = `${OT_API_URL}/activities-of-daily-living`;
const ASSISTIVE_DEVICE_ENDPOINT = `${OT_API_URL}/assistive-devices`;
const SCHOOL_READINESS_ENDPOINT = `${OT_API_URL}/classroom-behaviour`;
const SENSORY_PROCESS_ENDPOINT = `${OT_API_URL}/sensory-processing`;

const GET_SPEECH_THERAPIST_STUDENTS_DETAIL_API_URL = `${API_URL}/special-educator/speech-student`;

const SUBMIT_SPEECH_THERAPIST_STUDENT_DETAILS = `${API_URL}/special-educator/speech-student-information`;

const GET_SELECT_ASSESSMENT_API = `${API_URL}/clinical-psychologist/form-list/therapist`;

const POST_SELECT_ASSESSMENT_API = `${API_URL}/clinical-psychologist/form-select/therapist`;
const SPEECH_THERAPIST_DASHBOARD_STATS = `${API_URL}/ot/stats`;
const SPEECH_THERAPIST_UPCOMING_SESSIONS = `${API_URL}/ot/upcoming-session`;
const SPEECH_THERAPIST_MY_STUDENTS = `${API_URL}/ot/students`;
const SPEECH_THERAPIST_ASSIGN_BOOKING = `${API_URL}/speech-therapist/assign-session`;

const SPEECH_THERAPIST_SPEECH_LANGUAGE_ASSESSMENT = `${API_URL}/clinical-psychologist/selected-form-list/therapist`;

/** Occupational Therapist */

const OCCUPATIONAL_THERAPIST_DASHBOARD_STATS = `${API_URL}/ot/stats`;
const OCCUPATIONAL_THERAPIST_UPCOMING_SESSIONS = `${API_URL}/ot/upcoming-session`;
const OCCUPATIONAL_THERAPIST_MY_STUDENTS = `${API_URL}/ot/students`;

const GET_OCCUPATIONAL_THERAPIST_STUDENT_DETAILS_API_URL = `${API_URL}/special-educator/ot-student`;

const SUBMIT_OT_STUDENT_INFORMATION = `${API_URL}/special-educator/ot-student-information`;

/* Student Profile */
const OCCUPATIONAL_THERAPIST_GET_DURATION = `${API_URL}/ot/get-duration-data`;
const OCCUPATIONAL_THERAPIST_LEVEL_OF_SUPPORT = `${API_URL}/ot/get-level-data`;

/* Student Profile */
const STUDENT_PERSONAL_DETAIL = `${API_URL}/students/`;
const STUDENT_ASSESMENT_DETAIL = `${STUDENT_PERSONAL_DETAIL}assessmentData/`;
const STUDENT_REMARK_DETAIL = `${STUDENT_PERSONAL_DETAIL}remarks/`;
const STUDENT_GOAL_SUBGOAL = `${STUDENT_PERSONAL_DETAIL}goals/`;
const STUDENT_SESSION_LOG = `${STUDENT_PERSONAL_DETAIL}sessions/`;
const CREATE_GOAL = `${API_URL}/ot/create-goal`;
const GET_BOOKING_SLOT_TIME = `${API_URL}/speech-therapist/available-slot`;

/** Special Educator */
const SPECIAL_EDUCATOR_URL = `${API_URL}/special-educator`;
const SUBMIT_LANGUAGE_RECEIPT_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-language-receptive`;
const SUBMIT_LANGUAGE_EXPRESSION_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-language-expressive`;
const SUBMIT_VISUAL_PERCEPTION_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-visual-perception`;
const SUBMIT_WRITING_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-writing`;
const SUBMIT_FUNCTIONAL_READING_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-functional-reading`;
const SUBMIT_READING_SKILLS_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-reading-skills`;
const SUBMIT_MATHEMATICAL_SKILLS_ENDPOINT = `${SPECIAL_EDUCATOR_URL}/sec-mathematical-skills`;
/**
 * Speech Therapist
 */

const SPEECH_THERAPIST_URL = `${API_URL}/speech-therapist`;
const BEHAVIORAL_OBSERVATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-behavioral-observation`;
const DIAGNOSTIC_FORMULATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-diagnostic-formulation`;
const PROVISIONAL_DIAGNOSIS_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-provisional-diagnosis`;
const GSL_FORMAL_TOOLS_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-formal-tool-used`;
const IMPULSE_CONTROLE_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-attention-impulse-control-activity-level`;
const GSL_SENSORY_PROFILE_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-sensory-profile-observed`;
const CP_PROVISIONAL_DIAGNOSIS_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-provisional-diagnosis`;
const FORMAL_INFORMAL_TOOLS_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-formal-informal-tools-used`;
const CP_FORMAL_INFORMAL_TOOLS_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-formal-informal-tool-used`;
const DIAGNOSIS_IMPRESSION_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-diagnostic-impression`;
const CP_DIAGNOSIS_IMPRESSION_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-diagnostic-impression`;
const RECOMMENDATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-recommendations`;
const SUBMIT_MEDICAL_DEVELOPMENTAL_HISTORY_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-cerebral-palsy-history`;
const SUBMIT_MEDICAL_SURGERY_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-cleft-lip-palate-history`;
const SUBMIT_DEVELOPMENTAL_MILESTONE_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-developmental-milestones`;
const SUBMIT_SPEECH_ARTICULATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-speech-articulation`;
const SUBMIT_RESONANCE_AND_VOICE_ENDPOINT = `${SPEECH_THERAPIST_URL}/clp-resonance-voice`;
const SUBMIT_ALTERNATE_MODES_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-aac-alternate-modes`;
const SUBMIT_FLUENCY_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-case-history`;
const SUBMIT_OBSERVATIONAL_FINDING_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-observational-findings`;
// eslint-disable-next-line max-len
const SUBMIT_IMPACT_ON_FUNCTIONAL_COMMUNICATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-impact-functional-communication`;
const SUBMIT_SEVERITY_RATING_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-severity-rating`;
const SUBMIT_CLINICAL_IMPRESSION_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-clinical-impression`;
const SUBMIT_VOICE_CASE_HISTORY_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-case-history-voice-specific`;
// eslint-disable-next-line max-len
const SUBMIT_BEHAVIORAL_CLINICAL_OBSERVATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-behavioral-clinical-observations`;
const VOICE_PERCEPTION_ANALYSIS_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-perception-analysis`;
const VOICE_RECOMMENDATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-recommendations`;
// eslint-disable-next-line max-len
const VOICE_AERODYNAMIC_PHYSCOLOGICAL_ASPECTS_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-aerodynamic-physiological-aspects`;
const IMPACT_ON_COMMUNICATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-impact-communication-psychosocial-functioning`;
const VOICE_FORMAL_TOOLS_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-formal-tools-used`;
const VOICE_DIAGNOSTIC_IMPRESSION_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-diagnostic-impression`;
const SSD_DIAGNOSTIC_IMPRESSION_ENDPOINT = `${SPEECH_THERAPIST_URL}/ssd-diagnostic-impression`;
const SSD_FORMAL_AND_INFORMAL_ENDPOINT = `${SPEECH_THERAPIST_URL}/ssd-formal-informal-tools`;
const SSD_SPEECH_PHONOLOGY_ENDPOINT = `${SPEECH_THERAPIST_URL}/ssd-speech-phonology`;
const SSD_COMMUNICATION_PROFILE_ENDPOINT = `${SPEECH_THERAPIST_URL}/ssd-communication-profile`;
const VOICE_ACOUSTIC_ANALYSIS_ENDPOINT = `${SPEECH_THERAPIST_URL}/voice-acoustic-analysis`;
const GSL_SPEECH_RECOMMENDATION = `${SPEECH_THERAPIST_URL}/gsl-recommendations`;
const SSD_RECOMMENDATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/ssd-recommendations`;
const CP_RECOMMENDATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/cp-recommendations`;
const FLUENCY_RECOMMENDATION_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-recommendations`;
const FLUENCY_CHARACTER_STICKS_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-characteristics`;
const FLUENCY_ASSOCIATED_BEHAVIORS_ENDPOINT = `${SPEECH_THERAPIST_URL}/flc-associated-secondary-behaviors`;
const GSL_COMMUNICATION_PROFILE_ENDPOINT = `${SPEECH_THERAPIST_URL}/gsl-communication-profile`;
const ORAL_PERIPHERAL_MECHANISMS_EXAMINATION = `${SPEECH_THERAPIST_URL}/ssd-oral-peripheral-mechanism-examination`;
const VOICE_ORAL_PERIPHERAL_EXAMINATION = `${SPEECH_THERAPIST_URL}/voice-oral-peripheral-mechanism-examination`;
const CLP_ORAL_PERIPHERAL_EXAMINATION = `${SPEECH_THERAPIST_URL}/clp-oral-peripheral-mechanism-exam`;
const CP_ORAL_PERIPHERAL_EXAMINATION = `${SPEECH_THERAPIST_URL}/cp-oral-peripheral-mechanism`;

export {
    LOGIN_ENDPOINT,
    USER_TYPE_ENDPOINT,
    ROLE_MASTER_ENDPOINT,
    MENU_MASTER_ENDPOINT,
    SUPER_ADMIN_COMPILENCE_TRACKER,
    SUPER_ADMIN_DASHBOARD_STATS,
    SUPER_ADMIN_CENTER_OVERVIEW,
    SUPER_ADMIN_RECENT_ACTIVITY,
    CREATE_USER_TYPE_ENDPOINT,
    UPDATE_USER_TYPE_ENDPOINT,
    USER_TYPE_STATUS_ENDPOINT,
    ROLE_MASTER_STATUS_ENDPOINT,
    CENTER_SETUP_LIST,
    CENTER_ADMIN_DROPDOWN_LIST,
    CENTER_STATUS,
    CENTER_ADMIN_LIST,
    ROLE_MENU_MAPPING,
    CENTER_ADMIN_SPECIALIZATION,
    CENTER_DROPDOWN_LIST_API,
    CREATE_MENU_MASTER_ENDPOINT,
    UPDATE_MENU_MASTER_ENDPOINT,
    MENU_MASTER_STATUS_ENDPOINT,
    CENTER_ADMIN_STATUS,
    ADMIN_DASHBOARD_STATS,
    ADMIN_UPCOMNG_SESSIONS,
    ADMIN_RECENT_ACTIVITY,
    ADMIN_SESSION_LIST,
    ADMIN_STAFF_MANAGEMENT_API,
    ADMIN_LANGUAGE,
    GET_PSYCHOLOGIST_ENDPOINT,
    ADD_NEW_STAFF_MEMBER,
    GET_STUDENT_DETAIL_API_URL,
    SUBMIT_STUDENT_INFORMATION_API_URL,
    FORM_LIST_API_URL,
    SUBMIT_PERSONAL_BIRTH_HISTORY_ENDPOINT,
    SUBMIT_POST_NATAL_ENDPOINT,
    SUBMIT_MEDICAL_HISTORY_ENDPOINT,
    SUBMIT_FAMILY_HISTORY_ENDPOINT,
    SOCIAL_ENVIRONMENTAL_HISTORY_ENDPOINT,
    SCHOLASTIC_HISTORY_ENDPOINT,
    PLAY_HISTORY_ENDPOINT,
    GENERAL_OBSERVATION_ENDPOINT,
    SUBMIT_DIAGNOSIS_ENDPOINT,
    GET_CLINICAL_PSYCHOLOGIST_FORM_DETAILS,
    SUBMIT_NEO_NATAL_ENDPOINT,
    SUBMIT_GROSS_MOTOR_DEVELOPMENT_ENDPOINT,
    SUBMIT_DEVELOPMENTAL_FINE_MOTOR_ENDPOINT,
    SUBMIT_LANGUAGE_DEVELOPMENT_ENDPOINT,
    SUBMIT_SOCIAL_DEVELOPMENT_ENDPOINT,
    SUBMIT_SELF_HELP_ENDPOINT,
    GET_GRADE_ENDPOINT,
    GET_SCHOOL_ENDPOINT,
    ADD_STUDENT_ENDPOINT,
    CLINICAL_PSYCHOLOGIST_DASHBOARD_STATS,
    CLINICAL_PSYCHOLOGIST_UPCOMNG_SESSIONS,
    CLINICAL_PSYCHOLOGIST_RECENT_ACTIVITY,
    CLINICAL_PSYCHOLOGIST_ASSESSMENT_STUDENT_LIST,
    CLINICAL_PSYCHOLOGIST_TRACK_SESSION,
    ASSIGN_STUDENT_SESSION,
    GET_STUDENT_LIST,
    GET_STUDENT_ASSIGN_LIST_DETAILS,
    SPECIAL_EDUCATOR_DASHBOARD_STATS,
    SPECIAL_EDUCATOR_UPCOMING_SESSIONS,
    SPECIAL_EDUCATOR_MY_STUDENTS,
    SPEECH_THERAPIST_DASHBOARD_STATS,
    SPEECH_THERAPIST_UPCOMING_SESSIONS,
    SPEECH_THERAPIST_MY_STUDENTS,
    OCCUPATIONAL_THERAPIST_DASHBOARD_STATS,
    OCCUPATIONAL_THERAPIST_UPCOMING_SESSIONS,
    OCCUPATIONAL_THERAPIST_MY_STUDENTS,
    SPECIAL_EDUCATOR_ASSESSMENT_STUDENT_LIST,
    SPECIAL_EDUCATOR_INTERVENTION,
    MAP_STUDENT_ENDPOINT,
    STUDENT_PERSONAL_DETAIL,
    STUDENT_ASSESMENT_DETAIL,
    STUDENT_REMARK_DETAIL,
    STUDENT_GOAL_SUBGOAL,
    STUDENT_SESSION_LOG,
    CHIEF_COMPLAINTS_OBSERVATIONS_ENDPOINT,
    COMPLIANT_DETAIL_ANALYSIS_ENDPOINT,
    GROSS_MOTOR_SKILLS_ENDPOINT,
    MUSCLE_TONE_ENDPOINT,
    MUSCLE_STRENGTH_ENDPOINT,
    ROM_ENDPOINT,
    SPEED_AND_AGILITY_ENDPOINT,
    ENDURANCE_ENDPOINT,
    REFLEXES_ENDPOINT,
    FINE_MOTOR_SKILLS_ENDPOINT,
    GRASP_DEVELOPMENT_ENDPOINT,
    IN_HAND_DEVELOPMENT_ENDPOINT,
    CO_ORDINATION_ENDPOINT,
    NON_EQUILIBRIUM_ENDPOINT,
    COGNITIVE_AND_PERCEPTUAL_SKILLS_ENDPOINT,
    COMMUNICATION_SKILLS_ENDPOINT,
    EMOTIONAL_AWARENESS_ENDPOINT,
    SELF_REGULATION_ENDPOINT,
    BEHAVIOR_ENDPOINT,
    SUBMIT_SOCIAL_SKILLS_ENDPOINT,
    SUBMIT_PLAY_SKILLS_ENDPOINT,
    ACTIVITY_OF_DAILY_LIVING_ENDPOINT,
    ASSISTIVE_DEVICE_ENDPOINT,
    SCHOOL_READINESS_ENDPOINT,
    GET_OCCUPATIONAL_THERAPIST_STUDENT_DETAILS_API_URL,
    SUBMIT_OT_STUDENT_INFORMATION,
    GET_SPECIAL_EDUCATOR_STUDENTS_DETAIL,
    SUBMIT_SPECIAL_EDUCATOR_STUDENTS_DETAIL,
    GET_SPEECH_THERAPIST_STUDENTS_DETAIL_API_URL,
    SUBMIT_SPEECH_THERAPIST_STUDENT_DETAILS,
    GET_SELECT_ASSESSMENT_API,
    POST_SELECT_ASSESSMENT_API,
    OCCUPATIONAL_THERAPIST_GET_DURATION,
    OCCUPATIONAL_THERAPIST_LEVEL_OF_SUPPORT,
    CREATE_GOAL,
    GET_BOOKING_SLOT_TIME,
    SPEECH_THERAPIST_ASSIGN_BOOKING,
    SENSORY_PROCESS_ENDPOINT,
    SUBMIT_LANGUAGE_RECEIPT_ENDPOINT,
    SUBMIT_LANGUAGE_EXPRESSION_ENDPOINT,
    SUBMIT_VISUAL_PERCEPTION_ENDPOINT,
    SUBMIT_WRITING_ENDPOINT,
    SUBMIT_FUNCTIONAL_READING_ENDPOINT,
    SUBMIT_READING_SKILLS_ENDPOINT,
    SUBMIT_MATHEMATICAL_SKILLS_ENDPOINT,
    SPEECH_THERAPIST_SPEECH_LANGUAGE_ASSESSMENT,
    BEHAVIORAL_OBSERVATION_ENDPOINT,
    DIAGNOSTIC_FORMULATION_ENDPOINT,
    PROVISIONAL_DIAGNOSIS_ENDPOINT,
    FORMAL_INFORMAL_TOOLS_ENDPOINT,
    DIAGNOSIS_IMPRESSION_ENDPOINT,
    RECOMMENDATION_ENDPOINT,
    SUBMIT_MEDICAL_DEVELOPMENTAL_HISTORY_ENDPOINT,
    HOME_ENVIRONMENT_ENDPOINT,
    EQUILIBRIUM_ENDPOINT,
    SUBMIT_MEDICAL_SURGERY_ENDPOINT,
    SUBMIT_DEVELOPMENTAL_MILESTONE_ENDPOINT,
    SUBMIT_SPEECH_ARTICULATION_ENDPOINT,
    SUBMIT_RESONANCE_AND_VOICE_ENDPOINT,
    SUBMIT_ALTERNATE_MODES_ENDPOINT,
    CP_PROVISIONAL_DIAGNOSIS_ENDPOINT,
    CP_DIAGNOSIS_IMPRESSION_ENDPOINT,
    CP_FORMAL_INFORMAL_TOOLS_ENDPOINT,
    SUBMIT_FLUENCY_ENDPOINT,
    SUBMIT_OBSERVATIONAL_FINDING_ENDPOINT,
    SUBMIT_IMPACT_ON_FUNCTIONAL_COMMUNICATION_ENDPOINT,
    SUBMIT_SEVERITY_RATING_ENDPOINT,
    SUBMIT_CLINICAL_IMPRESSION_ENDPOINT,
    SUBMIT_VOICE_CASE_HISTORY_ENDPOINT,
    SUBMIT_BEHAVIORAL_CLINICAL_OBSERVATION_ENDPOINT,
    VOICE_PERCEPTION_ANALYSIS_ENDPOINT,
    VOICE_AERODYNAMIC_PHYSCOLOGICAL_ASPECTS_ENDPOINT,
    IMPACT_ON_COMMUNICATION_ENDPOINT,
    VOICE_FORMAL_TOOLS_ENDPOINT,
    VOICE_DIAGNOSTIC_IMPRESSION_ENDPOINT,
    IMPULSE_CONTROLE_ENDPOINT,
    GSL_SENSORY_PROFILE_ENDPOINT,
    GSL_FORMAL_TOOLS_ENDPOINT,
    SSD_DIAGNOSTIC_IMPRESSION_ENDPOINT,
    SSD_FORMAL_AND_INFORMAL_ENDPOINT,
    SSD_SPEECH_PHONOLOGY_ENDPOINT,
    VOICE_ACOUSTIC_ANALYSIS_ENDPOINT,
    GSL_SPEECH_RECOMMENDATION,
    CP_RECOMMENDATION_ENDPOINT,
    VOICE_RECOMMENDATION_ENDPOINT,
    FLUENCY_RECOMMENDATION_ENDPOINT,
    SSD_RECOMMENDATION_ENDPOINT,
    SSD_COMMUNICATION_PROFILE_ENDPOINT,
    FLUENCY_CHARACTER_STICKS_ENDPOINT,
    FLUENCY_ASSOCIATED_BEHAVIORS_ENDPOINT,
    GSL_COMMUNICATION_PROFILE_ENDPOINT,
    ORAL_PERIPHERAL_MECHANISMS_EXAMINATION,
    VOICE_ORAL_PERIPHERAL_EXAMINATION,
    CLP_ORAL_PERIPHERAL_EXAMINATION,
    CP_ORAL_PERIPHERAL_EXAMINATION,
};
