export const EMOTIONAL_REGULATION_QUESTIONS = [
    {
        id: 100,
        key: 'q100',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Seems to have difficulty liking self (for example, low self-esteem)',
    },
    {
        id: 101,
        key: 'q101',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has trouble "growing up" (for example, reacts immaturely to situations)',
    },
    {
        id: 102,
        key: 'q102',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Is sensitive to criticisms',
    },
    {
        id: 103,
        key: 'q103',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has definite fears (for example, fears are predictable)',
    },
    {
        id: 104,
        key: 'q104',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Seems anxious',
    },
    {
        id: 105,
        key: 'q105',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Displays excessive emotional outbursts when unsuccessful at a task',
    },
    {
        id: 106,
        key: 'q106',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Expresses feeling like a failure',
    },
    {
        id: 107,
        key: 'q107',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Is stubborn or uncooperative',
    },
    {
        id: 108,
        key: 'q108',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has temper tantrums',
    },
    {
        id: 109,
        key: 'q109',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Poor frustration tolerance',
    },
    {
        id: 110,
        key: 'q110',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Cries easily',
    },
    {
        id: 111,
        key: 'q111',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Overly serious',
    },
    {
        id: 112,
        key: 'q112',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has difficulty making friends (for example, does not interact or participate in group play)',
    },
    {
        id: 113,
        key: 'q113',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has nightmares',
    },
    {
        id: 114,
        key: 'q114',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: 'Has fears that interfere with daily routine',
    },
    {
        id: 115,
        key: 'q115',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: "Doesn't have a sense of humor",
    },
    {
        id: 116,
        key: 'q116',
        type: 'L',
        unicode: '2764',
        category: 'emotional_regulation',
        label: "Doesn't express emotions",
    },
];

export const SCALE_OPTIONS = [
    { label: 'Always', value: 1 },
    { label: 'Frequently', value: 2 },
    { label: 'Occasionally', value: 3 },
    { label: 'Seldom', value: 4 },
    { label: 'Never', value: 5 },
];
