import { ChildInformationFormKeys, ChildInformationFormType } from '@/types/childInformationType';

export const textAreaFields = [
    { label: 'Chief Complaints', name: 'chiefComplaints' },
    { label: 'Predisposing Factors', name: 'predisposingFactors' },
    { label: 'Precipitating Factors', name: 'precipitatingFactors' },
    { label: 'Perpetuating Factors', name: 'perpetuatingFactors' },
    { label: 'Brief History', name: 'briefHistory' },
];

export const inputFields = [
    { label: 'Name of Child', name: ChildInformationFormKeys.CHILD_NAME, type: 'input' },
    { label: 'Date of Birth / Age', name: ChildInformationFormKeys.DOB, type: 'date' },
    { label: 'Gender', name: ChildInformationFormKeys.GENDER, type: 'input' },
    { label: 'Address', name: ChildInformationFormKeys.ADDRESS, type: 'input' },
    { label: "Father's Name", name: ChildInformationFormKeys.FATHER_NAME, type: 'input' },
    { label: "Mother's Name", name: ChildInformationFormKeys.MOTHER_NAME, type: 'input' },
    { label: 'Contact Number(s)', name: ChildInformationFormKeys.CONTACT_NUMBER, type: 'input' },
    {
        label: 'Educational Qualification of Father',
        name: ChildInformationFormKeys.FATHER_EDUCATION,
        type: 'input',
    },
    {
        label: 'Educational Qualification of Mother',
        name: ChildInformationFormKeys.MOTHER_EDUCATION,
        type: 'input',
    },
    {
        label: 'Occupation of Father',
        name: ChildInformationFormKeys.FATHER_OCCUPATION,
        type: 'input',
    },
    {
        label: 'Occupation of Mother',
        name: ChildInformationFormKeys.MOTHER_OCCUPATION,
        type: 'input',
    },
    { label: 'Languages Spoken at Home', name: ChildInformationFormKeys.LANGUAGES, type: 'input' },
    {
        label: 'Referred By (Doctor/Teacher/Other)',
        name: ChildInformationFormKeys.REFERRED_BY,
        type: 'input',
    },
    { label: 'Date of Visit', name: ChildInformationFormKeys.VISIT_DATE, type: 'date' },
    {
        label: "Informant's Name & Relationship to the child",
        name: ChildInformationFormKeys.INFORMANT,
        type: 'input',
    },
    {
        label: 'Reliability of Informant',
        name: ChildInformationFormKeys.RELIABILITY,
        type: 'input',
    },
    {
        label: 'Age at which problems were recognised',
        name: ChildInformationFormKeys.PROBLEM_RECOGNITION_AGE,
        type: 'input',
    },
    { label: 'Onset', name: 'onset', type: 'input' },
    { label: 'Course', name: 'course', type: 'input' },
    { label: 'Progress', name: 'progress', type: 'input' },
];

export const INITIAL_STATE: ChildInformationFormType = {
    [ChildInformationFormKeys.CHILD_NAME]: '',
    [ChildInformationFormKeys.DOB]: null,
    [ChildInformationFormKeys.GENDER]: '',
    [ChildInformationFormKeys.ADDRESS]: '',
    [ChildInformationFormKeys.FATHER_NAME]: '',
    [ChildInformationFormKeys.MOTHER_NAME]: '',
    [ChildInformationFormKeys.CONTACT_NUMBER]: '',
    [ChildInformationFormKeys.FATHER_EDUCATION]: '',
    [ChildInformationFormKeys.MOTHER_EDUCATION]: '',
    [ChildInformationFormKeys.FATHER_OCCUPATION]: '',
    [ChildInformationFormKeys.MOTHER_OCCUPATION]: '',
    [ChildInformationFormKeys.LANGUAGES]: '',
    [ChildInformationFormKeys.REFERRED_BY]: '',
    [ChildInformationFormKeys.VISIT_DATE]: null,
    [ChildInformationFormKeys.INFORMANT]: '',
    [ChildInformationFormKeys.RELIABILITY]: '',
    [ChildInformationFormKeys.CHIEF_COMPLAINTS]: '',
    [ChildInformationFormKeys.COURSE]: '',
    [ChildInformationFormKeys.PRECIPITATING_FACTORS]: '',
    [ChildInformationFormKeys.PREPETUATING_FACTORS]: '',
    [ChildInformationFormKeys.BRIEF_HISTORY]: '',
    [ChildInformationFormKeys.PRE_DISPOSING_FACTORS]: '',
    [ChildInformationFormKeys.ONSET]: '',
    [ChildInformationFormKeys.PROGRESS]: '',
    [ChildInformationFormKeys.PROBLEM_RECOGNITION_AGE]: '',
};

export const disableFieldMap: Record<string, string> = {
    [ChildInformationFormKeys.CHILD_NAME]: 'studentName',
    [ChildInformationFormKeys.DOB]: 'dob',
    [ChildInformationFormKeys.GENDER]: 'gender',
    [ChildInformationFormKeys.ADDRESS]: 'address',
    [ChildInformationFormKeys.CONTACT_NUMBER]: 'contact',
    [ChildInformationFormKeys.FATHER_NAME]: 'fatherName',
    [ChildInformationFormKeys.MOTHER_NAME]: 'motherName',
    [ChildInformationFormKeys.FATHER_EDUCATION]: 'fatherQualification',
    [ChildInformationFormKeys.MOTHER_EDUCATION]: 'motherQualification',
    [ChildInformationFormKeys.FATHER_OCCUPATION]: 'fatherOccupation',
    [ChildInformationFormKeys.MOTHER_OCCUPATION]: 'motherOccupation',
    [ChildInformationFormKeys.LANGUAGES]: 'languageSpoken',
    [ChildInformationFormKeys.REFERRED_BY]: 'referredBy',
    [ChildInformationFormKeys.VISIT_DATE]: 'dateOfVisit',
    [ChildInformationFormKeys.PROBLEM_RECOGNITION_AGE]: 'ageWhenProblemRecognized',
    [ChildInformationFormKeys.COURSE]: 'course',
    [ChildInformationFormKeys.CHIEF_COMPLAINTS]: 'chiefComplaints',
    [ChildInformationFormKeys.INFORMANT]: 'informantNameRelationship',
    [ChildInformationFormKeys.RELIABILITY]: 'reliabilityOfInformant',
    [ChildInformationFormKeys.ONSET]: 'onset',
    [ChildInformationFormKeys.PROGRESS]: 'progress',
    [ChildInformationFormKeys.BRIEF_HISTORY]: 'briefHistory',
};
