import React from 'react';
import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import Providers from './_providers';

import '../styles/_base.scss';

const inter = Inter({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'CBL CBA',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => (
    <html lang='en'>
        <body className={`${inter.style.fontFamily}`}>
            <Providers>{children}</Providers>
        </body>
    </html>
);

export default RootLayout;
