export enum QueryKeys {
    CENTER_ADMIN = 'centerAdmin',
    CENTER_ADMIN_DROPDOWN_LIST = 'centerAdminDropdownList',
    CENTER_LIST = 'centerList',
    USER_TYPE = 'userType',
    ROLE_MASTER_TYPE = 'roleMasterType',
    MENU_MASTER_TYPE = 'menuMasterType',
    MENU_MAPPING = 'menuMapping',
    SUP_COMPILENCE_TRACKER = 'supCompilenceTracker',
    CENTER_SPECIALIZATION = 'centerSpecialization',
    CENTER_DROPDOWN_LIST = 'centerDropdownList',
    ADMIN_SESSION = 'adminSession',
    ADMIN_STAFF_MANAGEMENT = 'adminStaffManagement',
    LANGUAGE = 'language',
    CASE_HISTORY_SIDEBAR_MENU = 'caseHistorySidebarMenu',
}
