// pageNameMap.ts
export const pageNameMap: Record<string, string> = {
    '/super-admin/dashboard': 'Dashboard',
    '/super-admin/center-setup': 'Center Management',
    '/super-admin/center-admin': 'Center Admin',
    '/super-admin/user-type': 'User Type Master',
    '/super-admin/role-master': 'Role Master',
    '/super-admin/menu-master': 'Menu Master',
    '/super-admin/menu-mapping': 'Menu Mapping',
    '/admin/dashboard': 'Dashboard',
    '/admin/student-list': 'Student List',
    '/admin/staff-list': 'Staff List',
    '/admin/sessions': 'Sessions',
    '/clinical-psychologist/dashboard': 'Dashboard',
    '/clinical-psychologist/assessment': 'Student List',
    '/clinical-psychologist/trackSession': 'Sessions',
    '/specialist/dashboard': 'Dashboard',
    '/specialist/assessment': 'Student List',
    '/specialist/intervention': 'Intervention',
    '/occupational-therapist/dashboard': 'Dashboard',
    '/occupational-therapist/intervention': 'Intervention',
    '/occupational-therapist/assessment': 'Student List',
    '/speech-therapist/dashboard': 'Dashboard',
    '/speech-therapist/assessment': 'Student List',
    '/speech-therapist/intervention': 'Intervention',
    '/occupational-therapist/assessment/child-info': 'Student List',
};
